=== bgautijonsson/cube_rankings/config/publish-schemas/head_to_head.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "head_to_head",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "player_a",
      "player_b",
      "a_wins",
      "b_wins"
    ],
    "properties": {
      "player_a": {
        "type": "string"
      },
      "player_b": {
        "type": "string"
      },
      "a_wins": {
        "type": "number"
      },
      "b_wins": {
        "type": "number"
      }
    }
  }
}

=== bgautijonsson/cube_rankings/data/publish/head_to_head.json
[
  {
    "player_a": "Binni",
    "player_b": "Einar",
    "a_wins": 2,
    "b_wins": 3
  },
  {
    "player_a": "Binni",
    "player_b": "Ingvi",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Binni",
    "a_wins": 6,
    "b_wins": 7
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Aron Ívars",
    "a_wins": 5,
    "b_wins": 2
  },
  {
    "player_a": "Diddi",
    "player_b": "Einar",
    "a_wins": 4,
    "b_wins": 5
  },
  {
    "player_a": "Diddi",
    "player_b": "Ingvi",
    "a_wins": 5,
    "b_wins": 3
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Diddi",
    "a_wins": 13,
    "b_wins": 10
  },
  {
    "player_a": "Hjalti",
    "player_b": "Styrmir",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Aron Ívars",
    "player_b": "Hjalti",
    "a_wins": 1,
    "b_wins": 6
  },
  {
    "player_a": "Oddur",
    "player_b": "Styrmir",
    "a_wins": 3,
    "b_wins": 5
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Tommi",
    "a_wins": 15,
    "b_wins": 11
  },
  {
    "player_a": "Einar",
    "player_b": "Tommi",
    "a_wins": 5,
    "b_wins": 6
  },
  {
    "player_a": "Ingvi",
    "player_b": "Tommi",
    "a_wins": 6,
    "b_wins": 6
  },
  {
    "player_a": "Anna",
    "player_b": "Binni",
    "a_wins": 2,
    "b_wins": 4
  },
  {
    "player_a": "Binni",
    "player_b": "Tommi",
    "a_wins": 8,
    "b_wins": 7
  },
  {
    "player_a": "Arnar",
    "player_b": "Tommi",
    "a_wins": 3,
    "b_wins": 5
  },
  {
    "player_a": "Diddi",
    "player_b": "Oddur",
    "a_wins": 12,
    "b_wins": 8
  },
  {
    "player_a": "Arnar",
    "player_b": "Einar",
    "a_wins": 5,
    "b_wins": 3
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Oddur",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Arnar",
    "player_b": "Oddur",
    "a_wins": 2,
    "b_wins": 0
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Einar",
    "a_wins": 2,
    "b_wins": 4
  },
  {
    "player_a": "Anna",
    "player_b": "Aron Gauti",
    "a_wins": 5,
    "b_wins": 4
  },
  {
    "player_a": "Diddi",
    "player_b": "Tommi",
    "a_wins": 12,
    "b_wins": 10
  },
  {
    "player_a": "Arnar",
    "player_b": "Styrmir",
    "a_wins": 2,
    "b_wins": 0
  },
  {
    "player_a": "Binni",
    "player_b": "Oddur",
    "a_wins": 6,
    "b_wins": 1
  },
  {
    "player_a": "Daníel",
    "player_b": "Siggi",
    "a_wins": 1,
    "b_wins": 2
  },
  {
    "player_a": "Arnar",
    "player_b": "Binni",
    "a_wins": 2,
    "b_wins": 3
  },
  {
    "player_a": "Anna",
    "player_b": "Daníel",
    "a_wins": 2,
    "b_wins": 1
  },
  {
    "player_a": "Einar",
    "player_b": "Siggi",
    "a_wins": 2,
    "b_wins": 4
  },
  {
    "player_a": "Daníel",
    "player_b": "Oddur",
    "a_wins": 4,
    "b_wins": 3
  },
  {
    "player_a": "Diddi",
    "player_b": "Styrmir",
    "a_wins": 4,
    "b_wins": 2
  },
  {
    "player_a": "Siggi",
    "player_b": "Tommi",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Anna",
    "player_b": "Ingvi",
    "a_wins": 2,
    "b_wins": 1
  },
  {
    "player_a": "Styrmir",
    "player_b": "Tommi",
    "a_wins": 1,
    "b_wins": 4
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Aron Freyr",
    "a_wins": 7,
    "b_wins": 6
  },
  {
    "player_a": "Ingvi",
    "player_b": "Örvar",
    "a_wins": 2,
    "b_wins": 7
  },
  {
    "player_a": "Diddi",
    "player_b": "Örvar",
    "a_wins": 3,
    "b_wins": 9
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Örvar",
    "a_wins": 11,
    "b_wins": 9
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Ingvi",
    "a_wins": 3,
    "b_wins": 2
  },
  {
    "player_a": "Aron Ívars",
    "player_b": "Diddi",
    "a_wins": 6,
    "b_wins": 8
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Hjalti",
    "a_wins": 9,
    "b_wins": 5
  },
  {
    "player_a": "Aron Ívars",
    "player_b": "Ingvi",
    "a_wins": 2,
    "b_wins": 0
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Hjalti",
    "a_wins": 7,
    "b_wins": 6
  },
  {
    "player_a": "Örvar",
    "player_b": "Tommi",
    "a_wins": 16,
    "b_wins": 10
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Binni",
    "a_wins": 1,
    "b_wins": 2
  },
  {
    "player_a": "Aron Ívars",
    "player_b": "Einar",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Anna",
    "player_b": "Aron Freyr",
    "a_wins": 6,
    "b_wins": 5
  },
  {
    "player_a": "Aron Ívars",
    "player_b": "Binni",
    "a_wins": 10,
    "b_wins": 7
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Einar",
    "a_wins": 10,
    "b_wins": 5
  },
  {
    "player_a": "Anna",
    "player_b": "Aron Ívars",
    "a_wins": 3,
    "b_wins": 2
  },
  {
    "player_a": "Oddur",
    "player_b": "Siggi",
    "a_wins": 2,
    "b_wins": 1
  },
  {
    "player_a": "Arnar",
    "player_b": "Einar Logi",
    "a_wins": 2,
    "b_wins": 1
  },
  {
    "player_a": "Diddi",
    "player_b": "Siggi",
    "a_wins": 1,
    "b_wins": 2
  },
  {
    "player_a": "Oddur",
    "player_b": "Tommi",
    "a_wins": 8,
    "b_wins": 10
  },
  {
    "player_a": "Arnar",
    "player_b": "Siggi",
    "a_wins": 1,
    "b_wins": 2
  },
  {
    "player_a": "Diddi",
    "player_b": "Victor",
    "a_wins": 5,
    "b_wins": 7
  },
  {
    "player_a": "Anna",
    "player_b": "Tommi",
    "a_wins": 3,
    "b_wins": 2
  },
  {
    "player_a": "Anna",
    "player_b": "Victor",
    "a_wins": 2,
    "b_wins": 1
  },
  {
    "player_a": "Oddur",
    "player_b": "Örvar",
    "a_wins": 1,
    "b_wins": 8
  },
  {
    "player_a": "Anna",
    "player_b": "Örvar",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Hjalti",
    "player_b": "Siggi",
    "a_wins": 2,
    "b_wins": 0
  },
  {
    "player_a": "Hjalti",
    "player_b": "Ingvi",
    "a_wins": 1,
    "b_wins": 4
  },
  {
    "player_a": "Einar",
    "player_b": "Ingvi",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Ólafur",
    "player_b": "Tommi",
    "a_wins": 2,
    "b_wins": 4
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Aron Gauti",
    "a_wins": 7,
    "b_wins": 3
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Siggi",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Einar",
    "player_b": "Ólafur",
    "a_wins": 3,
    "b_wins": 2
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Ólafur",
    "a_wins": 1,
    "b_wins": 4
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Diddi",
    "a_wins": 4,
    "b_wins": 3
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Oddur",
    "a_wins": 11,
    "b_wins": 8
  },
  {
    "player_a": "Binni",
    "player_b": "Diddi",
    "a_wins": 6,
    "b_wins": 8
  },
  {
    "player_a": "Binni",
    "player_b": "Hjalti",
    "a_wins": 3,
    "b_wins": 3
  },
  {
    "player_a": "Anna",
    "player_b": "Ólafur",
    "a_wins": 2,
    "b_wins": 0
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Diddi",
    "a_wins": 2,
    "b_wins": 2
  },
  {
    "player_a": "Anna",
    "player_b": "Diddi",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Oddur",
    "player_b": "Ólafur",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Anna",
    "player_b": "Oddur",
    "a_wins": 1,
    "b_wins": 2
  },
  {
    "player_a": "Ólafur",
    "player_b": "Victor",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Örvar",
    "player_b": "Victor",
    "a_wins": 4,
    "b_wins": 2
  },
  {
    "player_a": "Ólafur",
    "player_b": "Örvar",
    "a_wins": 3,
    "b_wins": 5
  },
  {
    "player_a": "Aron Ívars",
    "player_b": "Daníel",
    "a_wins": 2,
    "b_wins": 2
  },
  {
    "player_a": "Daníel",
    "player_b": "Diddi",
    "a_wins": 2,
    "b_wins": 6
  },
  {
    "player_a": "Aron Ívars",
    "player_b": "Tommi",
    "a_wins": 2,
    "b_wins": 5
  },
  {
    "player_a": "Einar",
    "player_b": "Victor",
    "a_wins": 1,
    "b_wins": 2
  },
  {
    "player_a": "Einar",
    "player_b": "Oddur",
    "a_wins": 2,
    "b_wins": 0
  },
  {
    "player_a": "Oddur",
    "player_b": "Victor",
    "a_wins": 1,
    "b_wins": 2
  },
  {
    "player_a": "Diddi",
    "player_b": "Ólafur",
    "a_wins": 6,
    "b_wins": 0
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Ingvi",
    "a_wins": 3,
    "b_wins": 5
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Ólafur",
    "a_wins": 2,
    "b_wins": 1
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Daníel",
    "a_wins": 1,
    "b_wins": 6
  },
  {
    "player_a": "Binni",
    "player_b": "Victor",
    "a_wins": 4,
    "b_wins": 0
  },
  {
    "player_a": "Aron Freyr",
    "player_b": "Aron Ívars",
    "a_wins": 2,
    "b_wins": 4
  },
  {
    "player_a": "Binni",
    "player_b": "Daníel",
    "a_wins": 3,
    "b_wins": 3
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Ólafur",
    "a_wins": 4,
    "b_wins": 0
  },
  {
    "player_a": "Anna",
    "player_b": "Einar",
    "a_wins": 0,
    "b_wins": 2
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Einar",
    "a_wins": 2,
    "b_wins": 4
  },
  {
    "player_a": "Ingvi",
    "player_b": "Ólafur",
    "a_wins": 2,
    "b_wins": 1
  },
  {
    "player_a": "Hjalti",
    "player_b": "Örvar",
    "a_wins": 3,
    "b_wins": 3
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Hjalti",
    "a_wins": 2,
    "b_wins": 3
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Ingvi",
    "a_wins": 1,
    "b_wins": 2
  },
  {
    "player_a": "Diddi",
    "player_b": "Hjalti",
    "a_wins": 3,
    "b_wins": 2
  },
  {
    "player_a": "Daníel",
    "player_b": "Örvar",
    "a_wins": 3,
    "b_wins": 3
  },
  {
    "player_a": "Aron Gauti",
    "player_b": "Tommi",
    "a_wins": 1,
    "b_wins": 4
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Aron Gauti",
    "a_wins": 2,
    "b_wins": 0
  },
  {
    "player_a": "Binni",
    "player_b": "Örvar",
    "a_wins": 4,
    "b_wins": 6
  },
  {
    "player_a": "Aron Elvar",
    "player_b": "Binni",
